### ISSUE TITLE
How is the application different from all the other algorithms/applications currently detecting sarcasm ?

### ISSUE THREAD

**Issue by ihetal** [SJSUFall2019-CMPE272/SarcasmDetect#1]
I understand from the abstract that you feel social media analysis rely on past data. But you can get the current feed from Twitter, Facebook etc. And isn't it the same with news headlines as well. It contains past articles as well as current happenings. So what is the differentiating factor that will help out a business?

Also, news is a generic report about a current happening and usually does not contain much information about public sentiments about a product. How will you bring the correlation between a current happening to a product for it to be useful for the business ?

**Comment by pranavpatilsce** [comment]
You asked: So what is the differentiating factor that will help out a business?
Answer: I think there is some mis-understanding on what this project is trying to tackle. We are pulling tweets from twitter, real time. We trained out ML model on a dataset from Kaggle that has 1000s of past headlines and the dataset annotated each headline for sarcasm or no sarcasm. Once the model is trained on this, we take tweets from twitter and pass it to the ML model. The ML model then spits out if a tweet is sarcastic or not and we plan on using Stanford NLTK lib to do further NER on the tweets marked sarcastic. The business value comes from brands/businesses are able to get insight into a trend/hashtag related to them or their industry and see the sarcasm level and in which context is the sarcasm. The NER part allows the business to pinpoint it.

As for your 2nd question, I suggest you reread what our project really is. It's about sarcasm sentiment on Twitter, driven by a model trained on sarcastic/non-sarcastic headlines. No where do we say anything about news reports.

**Comment by pranavpatilsce** [comment]
For the last question, I guess part of the answer is Tableau and metrics/data shown there. We mentioned it in the tech choices area.
