### ISSUE TITLE
How can the contextual information be incorporated in making accurate predictions for sarcasm on an input text?

### ISSUE THREAD

**Issue by bhumikatiwari16** [SJSUFall2019-CMPE272/SarcasmDetect#2]
Human sarcasm is a product of human brain and we must not forget that the possibilities are numerous in which a human brain could frame words to express its opinion.  There is a complex relationship between sarcasm and sentiment as a feature, which could be hard to uncover using models and algorithms.
An example of a business use case of Sarcasm Detection for identifying the popularity of a product is mentioned below where it is difficult to comprehend the actual tone of the review texts for a product.

For IPhone handset, the social media post texts could be as below:
“Wow..Apple has launched such an awesome phone..IPhone 10.. I wish I had not donated my kidney earlier for IPhone6!”

For a certain kind of crafting paper, review text could be as below:
“I love this paper so much that I made a garbage bag out of it.”

The tone of these kind of texts is hard to be figured out, since it contains quite a lot of positive words, yet there is a tone of sarcasm in it as per human interpretation. 

Accuracy could be greater if the author’s information was incorporated into training data. Without contextual information (for example, author’s background info, responses, audience) consideration in the prediction algorithm and merely analyzing text content may not be appropriate to train the model.

**Comment by kalyanideshmukh11** [comment]
The train data set used  for the model is a labeled data set which helps model predict with the accuracy.
This model works on the tweets posted by the twitter users publicly and to get user's personal information is out of scope.
