### ISSUE TITLE
 Technology choices

### ISSUE THREAD

**Issue by narishtdhyani** [SJSUFall2019-CMPE272/SarcasmDetect#3]
1) If visualisation will be done using tableau, then what will be done using React js?
2) Which technology are you guys planning to use for developing API's for fetching data?
3) How you guys are planning to deploy tableau on Aws EC2?

**Comment by kalyanideshmukh11** [comment]
1.If visualisation will be done using tableau, then what will be done using React js?
Ans: React js is used for login to the application and manages the overall service. Tableau is used to create KPI's to provide key insights and help user drill down.

2.Which technology are you guys planning to use for developing API's for fetching data?
Ans: We have twitter streaming api's and python library to fetch data, train model and test the model using different machine learning models.

3.How you guys are planning to deploy tableau on Aws EC2?
Ans: Tableau has their own products such as tableau server and tableau online. we are using tableau online for server side live streaming of the data on the dashboard.
